Repository owid/covid-19-data, pull requests merged in 2021-08, with the labels that each got.

#1797 improve(yougov): replace date_end with date_mid
  scripts/src/cowidev/yougov/__main__.py
Labels: enhancement

#1842 feat(vax): add `total_boosters` metric
  public/data/README.md
  public/data/owid-covid-codebook.csv
  scripts/scripts/README.md.template
  scripts/scripts/megafile.py
  scripts/src/cowidev/vax/cmd/generate_dataset.py
  scripts/src/cowidev/vax/process/process.py
  scripts/src/cowidev/vax/utils/checks.py
Labels: enhancement, vaccinations

#1881 Update thailand.py
  scripts/scripts/testing/automated_sheets/Thailand.csv
  scripts/scripts/testing/automations/batch/thailand.py
Labels: tests
