Repository owid/covid-19-data, pull requests merged in 2021-11, with the labels that each got.

#2106 enhance(vax,ukraine): batch update, manufacturer data
  scripts/output/vaccinations/by_manufacturer/Ukraine.csv
  scripts/output/vaccinations/main_data/Ukraine.csv
  scripts/output/vaccinations/metadata/locations_manufacturer.csv
  scripts/src/cowidev/vax/batch/ukraine.py
  scripts/src/cowidev/vax/incremental/ukraine.py
Labels: vaccinations

#2110 Nigeria refactor
  scripts/scripts/testing/automations/incremental/nigeria.R
  scripts/scripts/testing/automations/incremental/nigeria.py
Labels: tests

#2117 Kenya refactor
  scripts/scripts/testing/automations/incremental/kenya.R
  scripts/scripts/testing/automations/incremental/kenya.py
Labels: tests

#2120 Create lebanon.py
  scripts/scripts/testing/automations/incremental/lebanon.R
  scripts/scripts/testing/automations/incremental/lebanon.py
Labels: tests

#2116 Tunisia refactor
  scripts/scripts/testing/automations/incremental/tunisia.R
  scripts/scripts/testing/automations/incremental/tunisia.py
Labels: tests

#2123 Azerbaijan refactor
  scripts/scripts/testing/automations/incremental/azerbaijan.R
  scripts/scripts/testing/automations/incremental/azerbaijan.py
Labels: tests

#2125 fix: subnational zip file gets created properly
  scripts/scripts/jhu.py
Labels: bug

#2131 India refactor
  scripts/scripts/testing/automations/batch/india.R
  scripts/scripts/testing/automations/batch/india.py
Labels: tests

#2151 feat(vax,denmark): add total_boosters
  scripts/src/cowidev/vax/batch/denmark.py
Labels: vaccinations

#2154 Uruguay, batch version for number of tests performed daily.
  scripts/scripts/testing/automations/batch/uruguay.py
  scripts/scripts/testing/automations/incremental/uruguay.R
Labels: tests

#2156 TEST: Add utils + migrate Bahrain to Python
  scripts/scripts/testing/automations/incremental/bahrain.R
  scripts/scripts/testing/automations/incremental/bahrain.py
  scripts/src/cowidev/testing/__init__.py
  scripts/src/cowidev/testing/utils/__init__.py
  scripts/src/cowidev/testing/utils/incremental.py
Labels: tests

#2158 refactor(test,bulgaria): migrate to python
  scripts/scripts/testing/automated_sheets/Bulgaria.csv
  scripts/scripts/testing/automations/incremental/bulgaria.R
  scripts/scripts/testing/automations/incremental/bulgaria.py
Labels: tests, refactor
