Repository owid/covid-19-data, pull requests merged in 2022-01, with the labels that each got.

#2217 Refactor(test,southkorea) migrate from r to python
  scripts/scripts/testing/automations/incremental/south_korea.R
  scripts/scripts/testing/automations/incremental/south_korea.py
Labels: tests

#2240 update taiwan.py and make it a bit more robust.
  scripts/src/cowidev/vax/incremental/taiwan.py
Labels: vaccinations

#2245 Update South Korea.csv
  scripts/scripts/testing/automated_sheets/South Korea.csv
Labels: tests

#2255 refactor(test): Liechtenstein
  scripts/scripts/testing/automated_sheets/Liechtenstein.csv
  scripts/scripts/testing/automations/batch/liechtenstein.py
Labels: tests

#2257 feat(hosp,japan): pull data from github csv
  scripts/src/cowidev/hosp/sources/japan.py
Labels: hospitalizations

#2264 Iran
  scripts/output/vaccinations/main_data/Iran.csv
  scripts/src/cowidev/vax/incremental/iran.py
  scripts/src/cowidev/vax/utils/orgs/who_config.yaml
Labels: vaccinations

#2271 (vax, iran) source change
  scripts/output/vaccinations/main_data/Iran.csv
  scripts/src/cowidev/vax/incremental/iran.py
Labels: vaccinations

#2272 (test, iran) python script
  scripts/scripts/testing/automated_sheets/Iran.csv
  scripts/scripts/testing/automations/incremental/iran.py
Labels: tests, vaccinations

#2275 Fix taiwan parser pdf link extraction
  scripts/output/vaccinations/main_data/Taiwan.csv
  scripts/src/cowidev/vax/incremental/taiwan.py
Labels: vaccinations

#2279 Testing Mexico
  scripts/scripts/testing/automations/batch/mexico.R
  scripts/scripts/testing/automations/batch/mexico.py
Labels: tests

#2262 refactor(south-korea): batch data collection
  scripts/scripts/testing/automated_sheets/South Korea.csv
  scripts/scripts/testing/automations/batch/south_korea.py
  scripts/scripts/testing/automations/incremental/south_korea.py
Labels: tests

#2283 Spain testing data
  scripts/scripts/testing/automated_sheets/Spain.csv
  scripts/scripts/testing/automations/batch/spain.py
Labels: tests

#2288 Albania test python script
  scripts/scripts/testing/automated_sheets/Albania.csv
  scripts/scripts/testing/automations/incremental/albania.py
  scripts/scripts/testing/automations/incremental/albania.r
  scripts/scripts/testing/automations/incremental/iran.R
Labels: tests

#2290 Finland use new data source for testing data
  scripts/scripts/testing/automated_sheets/Finland.csv
  scripts/scripts/testing/automations/batch/finland.py
Labels: tests

#2251 data(tests): africa cdc scraper
  scripts/scripts/testing/automated_sheets/Angola.csv
  scripts/scripts/testing/automated_sheets/Botswana.csv
  scripts/scripts/testing/automated_sheets/Burkina Faso.csv
  scripts/scripts/testing/automated_sheets/Burundi.csv
  scripts/scripts/testing/automated_sheets/Central African Republic.csv
  scripts/scripts/testing/automated_sheets/Chad.csv
  scripts/scripts/testing/automated_sheets/Kenya.csv
  scripts/scripts/testing/automated_sheets/Malawi.csv
  scripts/scripts/testing/automated_sheets/Mauritania.csv
  scripts/scripts/testing/automated_sheets/South Sudan.csv
  scripts/scripts/testing/automations/incremental/africacdc.py
  scripts/src/cowidev/testing/incremental/__init__.py
  scripts/src/cowidev/testing/incremental/africacdc.py
  scripts/src/cowidev/testing/utils/incremental.py
  scripts/src/cowidev/vax/incremental/africacdc.py
Labels: tests

#2293 (test, Georgia) script and data
  scripts/scripts/testing/automated_sheets/Georgia.csv
  scripts/scripts/testing/automations/incremental/georgia.py
Labels: tests

#2308 fixed(test,libya)
  scripts/scripts/testing/automated_sheets/Libya.csv
  scripts/scripts/testing/automations/incremental/libya.py
Labels: tests, priority:high

#2318 fix(ethiopia): change source to Africa CDC
  scripts/scripts/testing/automated_sheets/Ethiopia.csv
  scripts/scripts/testing/automations/batch/ethiopia.py
  scripts/src/cowidev/testing/incremental/africacdc.py
Labels: tests, priority:high

#2319 tests: sweden
  scripts/scripts/testing/automated_sheets/Sweden.csv
  scripts/scripts/testing/automations/incremental/sweden.R
Labels: tests, priority:high

#2322 test: austria
  scripts/scripts/testing/automated_sheets/Austria.csv
  scripts/scripts/testing/automations/batch/austria.py
  scripts/src/cowidev/testing/utils/utils.py
Labels: tests

#2313 fix(test,Laos) new script - new source (daily change)
  scripts/scripts/testing/automated_sheets/Laos.csv
  scripts/scripts/testing/automations/incremental/laos.py
Labels: tests, priority:high

#2302 Peru testing data
  scripts/scripts/testing/automated_sheets/Peru.csv
  scripts/scripts/testing/automations/batch/peru.R
  scripts/scripts/testing/automations/batch/peru.py
  scripts/src/cowidev/utils/web/download.py
Labels: tests, priority:high

#2311 (test, pakistan) python script
  scripts/scripts/testing/automated_sheets/Pakistan.csv
  scripts/scripts/testing/automations/incremental/pakistan.R
  scripts/scripts/testing/automations/incremental/pakistan.py
Labels: tests, priority:low

#2303 (test, australia) python and batch
  scripts/scripts/testing/automated_sheets/Australia.csv
  scripts/scripts/testing/automations/batch/australia.py
  scripts/scripts/testing/automations/incremental/australia.R
Labels: tests, priority:low

#2315 (test, Russia) python conversion
  scripts/scripts/testing/automated_sheets/Russia.csv
  scripts/scripts/testing/automations/incremental/russia.R
  scripts/scripts/testing/automations/incremental/russia.py
Labels: tests, priority:low

#2310 (test, Singapore) python script
  scripts/scripts/testing/automated_sheets/Singapore.csv
  scripts/scripts/testing/automations/batch/singapore.py
  scripts/scripts/testing/automations/incremental/singapore.R
  scripts/scripts/testing/testing_data_corrections.R
Labels: tests, priority:high

#2339 fix(tests,australia): remove daily change
  scripts/scripts/testing/automated_sheets/Australia.csv
  scripts/scripts/testing/automations/batch/australia.py
Labels: tests

#2337 data(tests,africa): automate more countires
  scripts/scripts/testing/automated_sheets/Gabon.csv
  scripts/scripts/testing/automated_sheets/Gambia.csv
  scripts/scripts/testing/automated_sheets/Namibia.csv
  scripts/src/cowidev/testing/incremental/africacdc.py
Labels: tests, priority:low

#2340 fix(pipeline): positive rate corrections
  scripts/scripts/testing/generate_dataset.R
  scripts/scripts/testing/testing_data_corrections.R
Labels: tests

#2331 refactor(test, sweden): python migration
  scripts/scripts/testing/automated_sheets/Sweden.csv
  scripts/scripts/testing/automations/incremental/sweden.R
  scripts/scripts/testing/automations/incremental/sweden.py
Labels: testing, refactor, priority:low

#2343 refactor(test, hong kong): python migration
  scripts/scripts/testing/automated_sheets/Hong Kong.csv
  scripts/scripts/testing/automations/batch/hong_kong.R
  scripts/scripts/testing/automations/batch/hong_kong.py
Labels: testing, refactor, priority:low

#2342 refactor(test, ukraine): python migration
  scripts/scripts/testing/automated_sheets/Ukraine.csv
  scripts/scripts/testing/automations/incremental/ukraine.R
  scripts/scripts/testing/automations/incremental/ukraine.py
Labels: testing, refactor, priority:low

#2348 refactor(test, Cape Verde): python migration
  scripts/scripts/testing/automated_sheets/Cape Verde.csv
  scripts/scripts/testing/automations/incremental/cape_verde.R
  scripts/scripts/testing/automations/incremental/cape_verde.py
Labels: testing, refactor, priority:low

#2335 data(tests,usa): calculate positive rate
  scripts/scripts/testing/automated_sheets/United States.csv
  scripts/scripts/testing/automations/batch/united_states.py
Labels: testing, priority:mid

#2349 refactor(test, philippines): python migration
  scripts/scripts/testing/automated_sheets/Philippines.csv
  scripts/scripts/testing/automations/batch/philippines.R
  scripts/scripts/testing/automations/batch/philippines.py
Labels: testing, refactor, priority:low

#2351 refactor(test, hungary): migrate to python
  scripts/scripts/testing/automated_sheets/Hungary.csv
  scripts/scripts/testing/automations/batch/hungary.R
  scripts/scripts/testing/automations/batch/hungary.py
Labels: testing, refactor, priority:low

#2358 fix(test, Russia)
  scripts/scripts/testing/automated_sheets/Russia.csv
  scripts/scripts/testing/automations/incremental/russia.py
Labels: bug, testing

#2357 refactor(test, Switzerland): Python migration
  scripts/scripts/testing/automated_sheets/Switzerland.csv
  scripts/scripts/testing/automations/batch/switzerland.R
  scripts/scripts/testing/automations/batch/switzerland.py
Labels: testing, priority:low

#2354 refactor(test, Fiji): migrate to python
  scripts/scripts/testing/automated_sheets/Fiji.csv
  scripts/scripts/testing/automations/batch/fiji.R
  scripts/scripts/testing/automations/incremental/fiji.py
Labels: testing, refactor, priority:low

#2377 refactor(vax, Thailand) : New source
  scripts/output/vaccinations/main_data/Thailand.csv
  scripts/requirements.txt
  scripts/src/cowidev/vax/incremental/thailand.py
Labels: vaccinations, refactor, priority:high

#2378 Automation(vax, Vietnam):New Script
  scripts/output/vaccinations/main_data/Vietnam.csv
  scripts/src/cowidev/vax/incremental/vietnam.py
Labels: vaccinations, priority:mid

#2307 El Salvador Testing Data
  scripts/scripts/testing/automated_sheets/El Salvador.csv
  scripts/scripts/testing/automations/batch/el_salvador.py
  scripts/scripts/testing/automations/incremental/el_salvador.py
Labels: testing, priority:high

#2372 refactor(vax, Azerbaijan): Changing dependencies
  scripts/output/vaccinations/main_data/Azerbaijan.csv
  scripts/src/cowidev/vax/incremental/azerbaijan.py
Labels: vaccinations, refactor, priority:low

#2382 (tests, fiji): collect cumulative total
  scripts/scripts/testing/automated_sheets/Fiji.csv
  scripts/scripts/testing/automations/incremental/fiji.py
Labels: testing, priority:low

#2383 refactor(vax, Kenya): Changing dependencies
  scripts/src/cowidev/vax/incremental/kenya.py
Labels: vaccinations, refactor, priority:low
